# The Docker image that will be used to build your app
image: node:lts
pages:
  script:
    - cp -r dist public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
